### ISSUE TITLE
Проблема от лекцията с клас Категори и релацията. 

### ISSUE THREAD

**Issue by MariaBonkova** [NikolayMarkov4/softuni-spring-web-2023-jan#33]
Привет Ники. Проблема го оправих, задачата тръгна, но по условие трабва да е с uuid, а ми тръгна с long в baseEntity. Реално не разбирам защо ми дава тази грешка като анотациите са ми верни. Притеснява ме че ако на изпита трябва да е с uuid няма да мога да го оправя. Между другото и Мобилелето ми не тръгна защото е с това id
@MappedSuperclass
public abstract class BaseEntityuuid {

    @Id
    @GeneratedValue(generator = "uuid-string")
    @GenericGenerator(name = "uuid-string",
            strategy = "org.hibernate.id.UUIDGenerator")

    private String id;

    public BaseEntityuuid() {
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }
}

**Comment by MariaBonkova** [comment]
Ники оправих проблема анотацията на id е трябвало на гетъра да я сложа. Радвам се, че се намерих грешката. Благодаря за съдействието.

**Comment by NikolayMarkov4** [comment]
Аз вчера споменах да провериш, дали анотациите са сложени на правилните места. Раздавам се, че проблема е решен.
